### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by amar-enkhbat** [bskim45/ccleaner-auto-update#6]
CCleanerAutoUpdate was working pretty well but juts recently it started giving me this error.

**Comment by oddMLan** [comment]
![image](https://user-images.githubusercontent.com/7278372/49330660-df745f00-f54e-11e8-9821-92e76bcddef1.png)

can confirm

**Comment by oddMLan** [comment]
change config.cfg
this line
`download_re: 		<a href="([^\"]+)">start the download</a>`
to this
`download_re: 		<a href="([^\"]+)" class="text-semibold">start the download</a>`

This works but I feel there should be a more fool-proof way to get the download url.

**Comment by bskim45** [comment]
Thanks for your report.

I'm going to release new version in few days, but until then please revise `download_re` section in `config.cfg` to:
`download_re: 		<a href="([^\"]+)" .+>start the download</a>`

**Comment by bskim45** [comment]
Anyway, I will consider a better way to handle it in future releases.
